- hosts: nginx-sites
  
  vars:
    nginx_listen_ipv6: false
    nginx_worker_processes: "{{ ansible_processor_vcpus|default(ansible_processor_count) }}"
    nginx_worker_connections: "1024"
    nginx_multi_accept: "off"
    nginx_sendfile: "on"
    nginx_tcp_nopush: "on"
    nginx_tcp_nodelay: "on"

    nginx_error_log: "/var/log/nginx/error.log warn"
    nginx_access_log: "/var/log/nginx/access.log main buffer=16k flush=2m"
    nginx_log_format: |-
      '$remote_addr - $remote_user [$time_local] "$request" '
      '$status $body_bytes_sent "$http_referer" '
      '"$http_user_agent" "$http_x_forwarded_for"'


    nginx_keepalive_timeout: "65"
    nginx_keepalive_requests: "100"

    nginx_client_max_body_size: "8m"
    nginx_server_names_hash_bucket_size: "64"

    nginx_extra_conf_options: |
      worker_rlimit_nofile 8192;

    nginx_vhosts:
      - listen: "443 ssl http2"
        server_name: "foundation.ru"
        server_name_redirect: "www.foundation.ru"
        root: "/var/www/foundation.ru"
        index: "index.php index.html index.htm"
        error_page: ""
        access_log: ""
        error_log: ""
        state: "present"
        template: "{{ nginx_vhost_template }}"
        filename: "foundation.ru.conf"
        extra_parameters: |
          location ~ \.php$ {
              fastcgi_split_path_info ^(.+\.php)(/.+)$;
              fastcgi_pass unix:/var/run/php5-fpm.sock;
              fastcgi_index index.php;
              fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
              include fastcgi_params;
          }
          ssl_certificate     /etc/ssl/certs/ssl-cert-snakeoil.pem;
          ssl_certificate_key /etc/ssl/private/ssl-cert-snakeoil.key;
          ssl_protocols       TLSv1.1 TLSv1.2;
          ssl_ciphers         HIGH:!aNULL:!MD5;

      - listen: "80"
        server_name: "foundation.ru www.foundation.ru"
        return: "301 https://foundation.ru$request_uri"
        filename: "foundation.ru.80.conf"


  roles:
    - { role: geerlingguy.nginx }
